language: c

jobs:
  include:
    - os: windows
      filter_secrets: false

env:
  - OMP_NUM_THREADS=4

addons:
  apt:
    packages:
      - libomp-dev
      - libopenmpi-dev
      - openmpi-bin
      - libgmp-dev
      - uuid-dev
  homebrew:
    packages:
      - libomp
      - open-mpi
      - gmp
      - ossp-uuid
      - argp-standalone
    update: true

before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install cygwin -y
        choco install cyg-get -y
        cyg-get gcc-core `
                gcc-g++ `
                libargp-devel `
                libgmp-devel `
                make
        export PATH=$PATH:/c/tools/cygwin/bin:/c/tools/cygwin/usr/bin
        ;;
    esac

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

script:
  - which cmake
  - cmake --version
  - cmake -G "MSYS Makefiles" ./CMakeLists.txt
  - cmake --build .
  - ./aes256_test
  - ./aes_validator --usage
  - ./aes_validator --help
  - ./aes_validator -rv -m3
  - |
    [[ $(./aes_validator -v -m3 78df66c7-4723-434f-b5b9-ae61e02cd97c \
        ddca0139c56a104940ecb16c9a64c689d18fa36c7d6bab71563dd0e540bdd028 \
        73962ffac2a737632b4e3dc0ce424dac) == \
      "ddca0139c56a104940ecb16c9a64c689d18fa36c7d63aa71543dd0e540bdd028" ]]
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./aes_validator_mpi --usage; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./aes_validator_mpi --help; fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then \
      mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
        ./aes_validator_mpi -rv -m3 \
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then \
      [[ $(mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
        ./aes_validator_mpi -v -m3 78df66c7-4723-434f-b5b9-ae61e02cd97c \
          ddca0139c56a104940ecb16c9a64c689d18fa36c7d6bab71563dd0e540bdd028 \
          73962ffac2a737632b4e3dc0ce424dac) == \
        "ddca0139c56a104940ecb16c9a64c689d18fa36c7d63aa71543dd0e540bdd028" ]] \
    fi
  - ./ecc256_test
  - ./ecc_validator --usage
  - ./ecc_validator --help
  - ./ecc_validator -rv -m2
  - |
    [[ $(./ecc_validator -v -m2 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f \
        d253229db92099808ace5668aa3c1b182a3857ebacbee5e67eeb0f5e422a1ce90f1f52b9ba6ea8242d469c6208f8ba304056181a85406542bf3a89b5badb1cee) == \
      "100102030405060718090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f" ]]
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./ecc_validator_mpi --usage; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./ecc_validator_mpi --help; fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then \
      mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
        ./ecc_validator_mpi -rv -m2 \
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then \
      [[ $(mpirun --oversubscribe --mca btl_base_warn_component_unused 0 -np 4 \
       ./ecc_validator_mpi -v -m2 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f \
          d253229db92099808ace5668aa3c1b182a3857ebacbee5e67eeb0f5e422a1ce90f1f52b9ba6ea8242d469c6208f8ba304056181a85406542bf3a89b5badb1cee) == \
         "100102030405060718090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f" ]] \
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/29fd40f0cf4a1a47b339
    # options: [always|never|change] default: always
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never