language: c

os:
  - linux
  - osx

osx_image: xcode10.1

compiler:
  - gcc
  - clang

env:
  - OMP_NUM_THREADS=4

dist: xenial

addons:
  apt:
    sources:
      - sourceline: "ppa:ondrej/php"
    packages:
      - libomp-dev
      - libgmp-dev
      - libssl-dev
      - uuid-dev
      - libsqlite3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp ossp-uuid cmake ; fi

script:
  - cmake --version
  - cmake ./CMakeLists.txt
  - cmake --build .
  - ./lookupwork
  - ./hamming_benchmark
  - ./hamming_validator

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/29fd40f0cf4a1a47b339
    # options: [always|never|change] default: always
    on_success: always
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never