language: c

os:
  - linux
  - osx

osx_image:
  - xcode10.1
  - xcode10.2

compiler:
  - gcc

env:
  - OMP_NUM_THREADS=4

dist: xenial

addons:
  apt:
    sources:
      - sourceline: "ppa:ondrej/php"
    packages:
      - libomp-dev
      - libopenmpi-dev
      - libgmp-dev
      - libssl-dev
      - uuid-dev
      - libsqlite3-dev
  homebrew:
    packages:
      - libomp
      - open-mpi
      - gmp
      - openssl@1.1
      - ossp-uuid
      - sqlite

# Based on Travis CI's recommendations for MPI projects
before_install:
  - test -n $CC && unset CC

script:
  - cmake --version
  - |
    # For Mojave (10.14)
    # Source: https://github.com/henry0312/LightGBM/blob/master/docs/Installation-Guide.rst#apple-clang
    if [[ "$TRAVIS_OSX_IMAGE" == "xcode10.2" ]]; then cmake \
      -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
      -DOpenMP_C_LIB_NAMES="omp" \
      -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
      -DOpenMP_CXX_LIB_NAMES="omp" \
      -DOpenMP_omp_LIBRARY=$(brew --prefix libomp)/lib/libomp.dylib \
      ./CMakeLists.txt
    else
      cmake ./CMakeLists.txt
  - cmake --build .
  - ./lookupwork
  - ./hamming_benchmark
  - ./hamming_validator

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/29fd40f0cf4a1a47b339
    # options: [always|never|change] default: always
    on_success: always
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never