language: c

jobs:
  include:
    - name: Ubuntu 20.04 (GCC)
      os: linux
      dist: focal
      compiler: gcc
    - name: Ubuntu 20.04 (Clang)
      os: linux
      dist: focal
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
        - OMP_NUM_THREADS=4
      before_script:
        - export LD_LIBRARY_PATH=/usr/lib/llvm-10/lib:$LD_LIBRARY_PATH;
    - name: macOS 10.15.7 (Catalina, Xcode 12.0.1)
      os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - OMP_NUM_THREADS=4
    - name: macOS 11.1 (Big Sur, Xcode 12.3)
      os: osx
      osx_image: xcode12.3
      compiler: clang
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - OMP_NUM_THREADS=4

env:
  - OMP_NUM_THREADS=4

addons:
  apt:
    packages:
      - clang-10
      - llvm-10-dev
      - libomp-dev
      - libopenmpi-dev
      - openmpi-bin
      - libgmp-dev
      - uuid-dev
      - libssl-dev
  homebrew:
    update: false
    packages:
      - libomp
      - gmp
      - ossp-uuid
      - argp-standalone
      - openssl@1.1.1

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - cmake ./CMakeLists.txt
  - cmake --build .
  - ./aes256_test
  - ./cipher_test
  - ./ecc_test
  - chmod u+x ./.travis/test_omp.sh
  - chmod u+x ./.travis/test_mpi.sh
  - ./.travis/test_omp.sh
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then ./.travis/test_mpi.sh; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/29fd40f0cf4a1a47b339
    # options: [always|never|change] default: always
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never