language: c

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - OMP_NUM_THREADS=4

dist: xenial

addons:
  apt:
    packages:
      - libomp-dev
      - libgmp-dev
      - uuid-dev
      - libsqlite3-dev

before_install:
  - wget https://www.openssl.org/source/openssl-1.1.0j.tar.gz
  - tar xvf openssl-1.1.0j.tar.gz
  - cd openssl-1.1.0j
  - sudo ./config
  - sudo make
  - sudo make install
  - cd ..

script:
  - cmake --version
  - cmake ./CMakeLists.txt
  - cmake --build .
  - ./lookupwork
  - ./hamming_benchmark
  - ./hamming_validator