language: c

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode10.1
      compiler: clang
    - os: osx
      osx_image: xcode10.2
      compiler: clang

env:
  - OMP_NUM_THREADS=4

addons:
  apt:
    packages:
      - libomp-dev
      - libopenmpi-dev
      - openmpi-bin
      - libgmp-dev
      - uuid-dev
      - libsqlite3-dev
  homebrew:
    packages:
      - libomp
      - open-mpi
      - gmp
      - ossp-uuid
      - sqlite

script:
  - cmake --version
  - |
    # For Mojave (10.14)
    # Source: https://github.com/henry0312/LightGBM/blob/master/docs/Installation-Guide.rst#apple-clang
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_OSX_IMAGE" == "xcode10.2" ]]; then cmake \
      -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
      -DOpenMP_C_LIB_NAMES="omp" \
      -DOpenMP_omp_LIBRARY=$(brew --prefix libomp)/lib/libomp.dylib \
      ./CMakeLists.txt
    else
      cmake ./CMakeLists.txt
    fi
  - cmake --build .
  - ./aes256_test
  - ./lookupwork
  - ./hamming_benchmark
  - ./hamming_validator
  - ./hamming_validator_fork
  - mpirun --oversubscribe -np 4 ./hamming_validator_mpi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/29fd40f0cf4a1a47b339
    # options: [always|never|change] default: always
    on_success: change
    # options: [always|never|change] default: always
    on_failure: always
    # options: [always|never|change] default: always
    on_start: never